INSERT INTO concern (CONCERN_NAME, LOCATION, YEAR_OF_FOUNDING) VALUES ('TestFirma', 'Frankfurt', 2000);
INSERT INTO concern (CONCERN_NAME, LOCATION, YEAR_OF_FOUNDING) VALUES ('BauFirma', 'Karlsruhe', 1974);
INSERT INTO concern (CONCERN_NAME, LOCATION, YEAR_OF_FOUNDING) VALUES ('ScheinFirma', 'Berlin', 2010);
INSERT INTO concern (CONCERN_NAME, LOCATION, YEAR_OF_FOUNDING) VALUES ('DieFirma', 'Köln', 2003);

INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (1, 'Jonas', 'Trautmann', 19, 'Darmstadt', 2, 'jonas@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (2, 'Tim', 'Müller', 19, 'Frankfurt', 3, 'tim@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (1, 'Theo', 'Schmidt', 19, 'Berlin', 6, 'theo@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (2, 'Karl', 'Schneider', 19, 'Kalrsruhe', 20, 'karl@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (3, 'Enes', 'Weber', 19, 'Köln', 9, 'enes@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (3, 'Robin', 'Bekcer', 19, 'Bremen', 1, 'robin@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (2, 'Janik', 'Schulz', 19, 'Hannover', 10, 'janik@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (3, 'Benedict', 'Richter', 19, 'Mainz', 3, 'benedict@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (3, 'Simon', 'Klein', 19, 'München', 4, 'simon@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (1, 'Daniel', 'Schröder', 19, 'Augsburg', 5, 'daniel@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (2, 'Monte', 'Wolf', 19, 'Kassel', 7, 'monte@gmx.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (4, 'Max', 'Braun', 19, 'Zwickau', 6, 'maxt@web.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (4, 'Phil', 'Zimmermann', 19, 'Koblenz', 11, 'phil@web.de');
INSERT INTO employee(CONCERN_ID, FIRST_NAME, LAST_NAME, AGE, PLACE_OF_RESIDENCE, SENIORITY, EMAIL) VALUES (4, 'Fabian', 'Lange', 19, 'Langen', 4, 'fabian@web.de');
